In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel("deforestation_finaladata.xlsx")
data.head()

,country,iso_code,year,forest_area_sqkm,forest_loss_sqkm,deforestation_rate_percent,agricultural_land_sqkm,agricultural_expansion_sqkm,cattle_count,cattle_density
0,DR Congo,COD,2021,5049024.11,7951.22,0.1575,2315109.32,4364.24,17055129.88,770.4552
1,Brazil,BRA,2009,868611.60,4374.97,0.5037,205205.97,4972.19,36330173.29,117.8415
2,India,IND,2019,2728978.73,3218.11,0.1179,1349663.81,2891.33,49948266.89,100.7117
3,Argentina,ARG,2022,6932579.83,2137.05,0.0308,1562392.81,2307.29,48016746.24,99.4208
4,Indonesia,IDN,2002,4011789.45,1935.78,0.0483,894703.70,3694.49,4204812.69,4.7414

In [3]:
data.info()
print("Shape of dataset:", data.shape)
print("Columns:\n", data.columns)

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   country                      15000 non-null  str
 1   iso_code                     15000 non-null  str
 2   year                         15000 non-null  int64
 3   forest_area_sqkm             15000 non-null  float64
 4   forest_loss_sqkm             15000 non-null  float64
 5   deforestation_rate_percent   15000 non-null  float64
 6   agricultural_land_sqkm       15000 non-null  float64
 7   agricultural_expansion_sqkm  15000 non-null  float64
 8   cattle_count                 15000 non-null  float64
 9   cattle_density               15000 non-null  float64
dtypes: float64(7), int64(1), str(2)
memory usage: 1.1 MB
Shape of dataset: (15000, 10)
Columns:
 Index(['country', 'iso_code', 'year', 'forest_area_sqkm', 'forest_loss_sqkm',
       'deforestation_rate_percent', 'agricultural_land_sqkm',
       'agricultural_expansion_sqkm', 'cattle_count', 'cattle_density'],
      dtype='str')

In [4]:
data.isnull().sum()
num_cols = data.select_dtypes(include=np.number).columns
data[num_cols] = data[num_cols].fillna(data[num_cols].mean())
cat_cols = data.select_dtypes(include='object').columns
for col in cat_cols:
    data[col] = data[col].fillna(data[col].mode()[0])

C:\Users\HP\AppData\Local\Temp\ipykernel_1456\2188874210.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = data.select_dtypes(include='object').columns

In [5]:
print("Duplicate rows:", data.duplicated().sum())
data = data.drop_duplicates()

Duplicate rows: 0

In [6]:
data.columns = data.columns.str.strip().str.lower().str.replace(" ", "_")
data.head()

,country,iso_code,year,forest_area_sqkm,forest_loss_sqkm,deforestation_rate_percent,agricultural_land_sqkm,agricultural_expansion_sqkm,cattle_count,cattle_density
0,DR Congo,COD,2021,5049024.11,7951.22,0.1575,2315109.32,4364.24,17055129.88,770.4552
1,Brazil,BRA,2009,868611.60,4374.97,0.5037,205205.97,4972.19,36330173.29,117.8415
2,India,IND,2019,2728978.73,3218.11,0.1179,1349663.81,2891.33,49948266.89,100.7117
3,Argentina,ARG,2022,6932579.83,2137.05,0.0308,1562392.81,2307.29,48016746.24,99.4208
4,Indonesia,IDN,2002,4011789.45,1935.78,0.0483,894703.70,3694.49,4204812.69,4.7414

In [7]:
if 'year' in data.columns:
    data['year'] = data['year'].astype(int)

In [8]:
for col in num_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    data = data[(data[col] >= Q1 - 1.5*IQR) & (data[col] <= Q3 + 1.5*IQR)]

In [9]:
data.reset_index(drop=True, inplace=True)

In [10]:
data.to_excel("deforestation_cleaned.xlsx", index=False)